# GitHub Actions: Pull Request CI Workflow

name: "🔀 [Workflow-8] Pull Request CI Workflow"

run-name: "🔀 [Workflow-8] ${{ github.actor }} → Running Pull Request CI"

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened
    paths : 
      - '08-Pull-Request-CI-Workflow/*'
      - '.github/workflows/08-Pull-Request-Based-Config-CI.yml'
   
jobs:
  pull_request_job:
    name: "Pull Request CI Job"
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v7
        with:
          node-version: '24'

      - run: echo "Pull Request CI is running"

      - run: cd 08-Pull-Request-CI-Workflow && npm install

      - run: cd 08-Pull-Request-CI-Workflow && npm run test